# Generated by Django 5.1.7 on 2025-04-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_whislist_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='Product',
            new_name='product',
        ),
    ]
